
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/marouane/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Linux - 5.15.137.3-microsoft-standard-WSL2 - x86_64
